name: build_only

on:
  push:
    branches-ignore:
      - '3.x'
      - '2.x'
      - '1.x'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build image (no push)
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: pantheonpublic/terminus-plugin-test:ci
