name: build_and_push

on:
  push:
    branches:
      - '4.x'

jobs:
  docker:
    runs-on: ubuntu-latest
    matrix:
        php-versions: ['7.4', '8.0']
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: pantheonpublic/terminus-plugin-test:4.x-php${{ matrix.php-versions }}
          build-args: |
            PHPVERSION=${{ matrix.php-versions }}
          push: true
